In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ["id","Unnamed: 32"],inplace = True)

## Train Test Split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [7]:

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.26715983,  0.69317414,  0.24921006, ...,  0.23363176,
         0.43033823,  0.43293179],
       [-0.81968708, -1.07175069, -0.85284361, ..., -1.51587186,
        -0.13767767, -0.58074766],
       [-0.64823262, -0.07010167, -0.67879078, ..., -0.71171029,
        -0.59470195, -0.26276311],
       ...,
       [ 1.49349512, -0.15919065,  1.42796497, ...,  1.43389578,
         1.04079209, -0.09630511],
       [ 0.04339723,  2.07525716,  0.03933521, ..., -0.511513  ,
        -1.64749003, -0.37170738],
       [ 0.03758522,  0.31274014,  0.03343511, ...,  0.28115179,
        -0.59633418, -0.33742035]])

In [9]:
X_test

array([[ 0.63331682,  0.06714351,  0.76631134, ...,  0.94949804,
         0.68333381,  0.36933488],
       [-1.26430627, -0.243464  , -1.30167235, ..., -1.771407  ,
        -1.61647767, -1.05578893],
       [-0.46806014, -1.54127367, -0.53887421, ..., -1.36058866,
        -1.01092049, -0.79642414],
       ...,
       [-0.94464541,  1.19881427, -0.95778103, ..., -1.27106706,
         0.26058635, -0.46572021],
       [-0.17745936, -0.11585006, -0.1760183 , ...,  0.41604736,
         1.00977973,  0.10886406],
       [ 0.24100576,  0.79430217,  0.44180605, ...,  2.02253102,
        -0.05443396,  1.70431699]])

In [10]:
y_train

413    B
333    B
211    B
235    B
481    B
      ..
340    B
219    M
56     M
238    B
476    B
Name: diagnosis, Length: 455, dtype: object

## Label Encoder

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [13]:
y_test

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1])

## Numpy Array to Pytorch Tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

## Define the Model

In [17]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__(),
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

## Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25

In [19]:
loss_function = nn.BCELoss()

## Training Pipeline

In [24]:
# Create Model
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor.float())

  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1).float())

  loss.backward()
  optimizer.zero_grad()
  # Parameters Update
  optimizer.step()
  # Typo: 'opimizer' should be 'optimizer'

  # Print Loss in each Epoch
  print(f"Epoch = {epoch} Loss = {loss.item()}")

Epoch = 0 Loss = 0.49082764983177185
Epoch = 1 Loss = 0.49082764983177185
Epoch = 2 Loss = 0.49082764983177185
Epoch = 3 Loss = 0.49082764983177185
Epoch = 4 Loss = 0.49082764983177185
Epoch = 5 Loss = 0.49082764983177185
Epoch = 6 Loss = 0.49082764983177185
Epoch = 7 Loss = 0.49082764983177185
Epoch = 8 Loss = 0.49082764983177185
Epoch = 9 Loss = 0.49082764983177185
Epoch = 10 Loss = 0.49082764983177185
Epoch = 11 Loss = 0.49082764983177185
Epoch = 12 Loss = 0.49082764983177185
Epoch = 13 Loss = 0.49082764983177185
Epoch = 14 Loss = 0.49082764983177185
Epoch = 15 Loss = 0.49082764983177185
Epoch = 16 Loss = 0.49082764983177185
Epoch = 17 Loss = 0.49082764983177185
Epoch = 18 Loss = 0.49082764983177185
Epoch = 19 Loss = 0.49082764983177185
Epoch = 20 Loss = 0.49082764983177185
Epoch = 21 Loss = 0.49082764983177185
Epoch = 22 Loss = 0.49082764983177185
Epoch = 23 Loss = 0.49082764983177185
Epoch = 24 Loss = 0.49082764983177185

In [26]:
model.linear.bias

Parameter containing:
tensor([0.1005], requires_grad=True)

## Evaluation

In [28]:
#model evaluation
## But Y_train is in the range between 0 or 1
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.75).float()
  accuracy = (y_pred == y_test_tensor.float()).float().mean()
  print(f"Accuracy = {accuracy}")

Accuracy = 0.561557412147522