In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns = ["id","Unnamed: 32"],inplace = True)

## Train Test Split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [9]:

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-1.86293345e+00,  1.25248775e+00, -1.86994814e+00, ...,
        -1.76683124e+00, -4.02281315e-02, -7.28519548e-01],
       [ 2.51392490e-01, -3.19979565e-02,  2.07953018e-01, ...,
        -3.73109055e-02, -1.02577874e+00, -7.75049696e-01],
       [-9.49335820e-01, -1.61001331e+00, -9.76290607e-01, ...,
        -1.27360910e+00, -1.25836199e+00, -9.45295296e-01],
       ...,
       [ 1.76245396e+00,  8.97903946e-01,  1.68783641e+00, ...,
         6.62218301e-01,  1.32849920e+00, -1.00700023e-03],
       [ 2.08438836e+00, -9.64248096e-01,  2.06265036e+00, ...,
         1.26909463e+00, -2.76157903e-01,  1.62122224e-01],
       [-1.33884744e+00, -7.74040889e-01, -1.35236797e+00, ...,
        -6.51599467e-01, -2.30979862e-01, -1.05015566e-01]])

In [11]:
X_test

array([[-0.80432032, -1.00651636, -0.79141047, ..., -0.79459374,
        -1.81388457, -0.51612311],
       [-0.83622373, -0.23864282, -0.7745649 , ...,  0.11402212,
         0.69098684,  2.51818995],
       [-0.74921443, -1.49494969, -0.75729819, ..., -0.46212434,
        -0.20588095,  0.21138944],
       ...,
       [ 0.32970086, -0.45468064,  0.45810974, ...,  1.67522307,
         0.6073238 ,  1.93793163],
       [-0.77241691, -1.00416813, -0.77709173, ..., -0.28314987,
        -0.38659312, -0.30701115],
       [-0.20975679, -0.10714154, -0.20560574, ...,  0.43676297,
         1.0423716 ,  0.16157481]])

In [12]:
y_train

568    B
514    M
296    B
208    B
224    B
      ..
145    B
103    B
95     M
372    M
234    B
Name: diagnosis, Length: 455, dtype: object

## Label Encoder

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [15]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0])

## Numpy Array to Pytorch Tensors

In [16]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

## Loading the Model

In [23]:
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return self.features.shape[1]
  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [24]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [29]:
train_loader = DataLoader(train_dataset,batch_size = 32,shuffle = True)
test_loader = DataLoader(test_dataset,batch_size = 32,shuffle = True)

## Define the Model

In [30]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__(),
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

## Important Parameters

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
loss_function = nn.BCELoss()

## Training Pipeline

In [35]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:
    y_pred = model(batch_features.float())
    loss = loss_function(y_pred,batch_labels.reshape(-1,1).float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f"Epoch = {epoch} Loss = {loss.item()}")

Epoch = 0 Loss = 0.800642728805542
Epoch = 1 Loss = 0.6099191308021545
Epoch = 2 Loss = 0.49931198358535767
Epoch = 3 Loss = 0.43008536100387573
Epoch = 4 Loss = 0.383131206035614
Epoch = 5 Loss = 0.34913793206214905
Epoch = 6 Loss = 0.323263019323349
Epoch = 7 Loss = 0.30279412865638733
Epoch = 8 Loss = 0.28610759973526
Epoch = 9 Loss = 0.2721754014492035
Epoch = 10 Loss = 0.26031604409217834
Epoch = 11 Loss = 0.25005945563316345
Epoch = 12 Loss = 0.24107083678245544
Epoch = 13 Loss = 0.2331049144268036
Epoch = 14 Loss = 0.22597767412662506
Epoch = 15 Loss = 0.2195482701063156
Epoch = 16 Loss = 0.21370668709278107
Epoch = 17 Loss = 0.20836590230464935
Epoch = 18 Loss = 0.20345589518547058
Epoch = 19 Loss = 0.19891968369483948
Epoch = 20 Loss = 0.1947103887796402
Epoch = 21 Loss = 0.19078899919986725
Epoch = 22 Loss = 0.18712282180786133
Epoch = 23 Loss = 0.18368412554264069
Epoch = 24 Loss = 0.18044941127300262

In [36]:
model.linear.bias

Parameter containing:
tensor([-0.1856], requires_grad=True)

## Evaluation

In [39]:
#model evaluation
## But Y_train is in the range between 0 or 1
model.eval()
accuracy_list = []

with torch.no_grad():

  ## accuracy is beign caluclated for every batch
  for batch_features,batch_labels in train_loader:
    y_pred = model(batch_features.float())
    y_pred = (y_pred>0.8).float()
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# Finally the overall accuracy is calcualted using the mean of all the accuary
  print(f"Accuracy = {np.mean(accuracy_list)}")

Accuracy = 0.8666666746139526