In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ["id","Unnamed: 32"],inplace = True)

## Train Test Split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.83444714,  1.14434781,  0.87881867, ...,  1.12907904,
         0.67682948,  2.67807833],
       [ 0.51081655, -0.87095868,  0.54101919, ...,  1.2541117 ,
         0.20006752,  0.37334347],
       [-0.14750892, -1.39659356, -0.1796197 , ..., -0.5381247 ,
        -0.83615999,  0.15399927],
       ...,
       [ 1.40702434,  1.58051292,  1.42975353, ...,  0.95525315,
         1.25899798,  1.51112397],
       [-0.41028589, -1.61803124, -0.46111927, ..., -0.51250826,
        -0.19561247,  0.55703073],
       [ 1.31574392,  0.42635293,  1.25683237, ...,  0.96135231,
        -0.55885967, -0.99620714]])

In [9]:
X_test

array([[-1.22959684e+00, -1.66276612e+00, -1.25092663e+00, ...,
        -1.76649432e+00,  3.39528501e-01, -1.52326253e-01],
       [-1.55239761e+00, -1.41001403e+00, -1.52076407e+00, ...,
        -4.68594349e-01,  1.41688506e-01,  1.11133405e+00],
       [-9.13711256e-01, -8.46354497e-01, -8.82162194e-01, ...,
        -5.51847801e-01, -5.10210492e-01,  1.27881361e+00],
       ...,
       [-4.54543069e-01, -6.89782406e-01, -4.46240007e-01, ...,
        -4.83994713e-01,  4.20610466e-01, -4.83503578e-01],
       [-3.13473325e-01, -1.82041480e-01, -2.91817388e-01, ...,
         1.51689613e-01,  3.52501615e-01, -6.26436489e-02],
       [-1.00485672e-01,  1.13763758e+00, -6.66407138e-04, ...,
         5.52708989e-01,  1.22494356e+00,  1.83527796e+00]])

In [10]:
y_train

72     M
330    M
220    B
257    M
156    M
      ..
91     M
472    B
33     M
418    B
70     M
Name: diagnosis, Length: 455, dtype: object

## Label Encoder

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1])

In [13]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1])

## Numpy Array to Pytorch Tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

## Define the Model

In [17]:
class mySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad = True)
    self.bias = torch.zeros(1,dtype = torch.float64, requires_grad = True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilion = 1e-7
    y_pred = torch.clamp(y_pred,epsilion,1-epsilion)
    loss = -(y*torch.log(y_pred+epsilion) + (1-y)*torch.log(1-y_pred+epsilion))
    return loss.mean()

## Important Parameters

In [18]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [19]:
# Create Model
model = mySimpleNN(X_train_tensor)

for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)

  loss = model.loss_function(y_pred,y_train_tensor)

  loss.backward()

  # Parameters Update
  with torch.no_grad(): ## In this Step we donot require the  Gradients
  ## we turn off the gradient using "with torch.no_grad()"
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print Loss in each Epoch
  print(f"Epoch = {epoch} Loss = {loss.item()}")

Epoch = 0 Loss = 3.8103987945533797
Epoch = 1 Loss = 3.6959034042660406
Epoch = 2 Loss = 3.576799788967218
Epoch = 3 Loss = 3.45293868810168
Epoch = 4 Loss = 3.3249007626067337
Epoch = 5 Loss = 3.192392959231824
Epoch = 6 Loss = 3.057945388743952
Epoch = 7 Loss = 2.9203158180366207
Epoch = 8 Loss = 2.780403250042564
Epoch = 9 Loss = 2.638326933149408
Epoch = 10 Loss = 2.4936825848809296
Epoch = 11 Loss = 2.349731019193724
Epoch = 12 Loss = 2.2070570190917698
Epoch = 13 Loss = 2.065702862616965
Epoch = 14 Loss = 1.927473918096081
Epoch = 15 Loss = 1.788423030003697
Epoch = 16 Loss = 1.6546207821362198
Epoch = 17 Loss = 1.5295519399132989
Epoch = 18 Loss = 1.4134550680434985
Epoch = 19 Loss = 1.3079816154339732
Epoch = 20 Loss = 1.2155038694049918
Epoch = 21 Loss = 1.1366548462091008
Epoch = 22 Loss = 1.0710619643409631
Epoch = 23 Loss = 1.0174837055674713
Epoch = 24 Loss = 0.9741169247038561

In [20]:
model.bias

tensor([-0.0967], dtype=torch.float64, requires_grad=True)

## Evaluation

In [24]:
#model evaluation
## But Y_train is in the range between 0 or 1
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.75).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy = {accuracy}")

Accuracy = 0.6131117343902588